version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      # Mapeia a pasta local para dentro do contêiner
      - ./mssql-init:/usr/src/app
      # Volume para persistir os dados do banco na sua máquina
      - mssql_data:/var/opt/mssql
    # Altera o entrypoint padrão para executar o script de inicialização
    entrypoint: /bin/bash /usr/src/app/entrypoint.sh

  app:
    build: .
    container_name: relatorio_app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_SERVER=db
      - DB_USER=${DB_USERENV}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - KAFKA_BROKERS=kafka:9092
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./src/public/uploads:/app/src/public/uploads
      - ./src/relatoriosGerados:/app/src/relatoriosGerados

  kafka:
    image: apache/kafka:3.7.0
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      - kafka

volumes:
  mssql_data:
    